--RIPULITURA TABELLE

--DROP TABLE SPEDIZIONE;
--DROP TABLE ORDINE;
--DROP TABLE CAMION;
--DROP TABLE AUTISTA;
--DROP TABLE GESTISCE;
--DROP TABLE MAGAZZINIERE;
--DROP TABLE ALLOCATO_IN;
--DROP TABLE REPARTO;
--DROP TABLE E_IN;
--DROP TABLE FATTURA;
--DROP TABLE PRODOTTO;
--DROP TABLE CARTA;
--DROP TABLE AZIENDA;
--DROP TABLE PERSONA;
--DROP TABLE CLIENTE;
--DROP TABLE FORNITURA;
--DROP TABLE INVENTARIO;
--DROP TABLE TELEFONO_SOCIETA;
--DROP TABLE FORNITORE;


--FORNITORE
CREATE TABLE FORNITORE ( 
   P_IVA_FORNITORE CHAR(11) PRIMARY KEY, 
   NOME_SOCIETA    VARCHAR2(25) NOT NULL UNIQUE, 
   VIA_F           VARCHAR2(25), 
   CITTA_F         VARCHAR2(25), 
   CAP_F           CHAR(5),
   NR_CIVICO_F     CHAR(3)
);


--TELEFONO FORNITORE (ATTRIBUTO MULTIVALORE DI FORNITORE) 
-- [SU FK_FORNITORE NON HO AGGIUNTO NESSUNA POLITICA DI REAZIONE]
CREATE TABLE TELEFONO_SOCIETA (  
    P_IVA_FORNITORE CHAR(11), 
    NUM_TEL_SOCIETA CHAR(17) NOT NULL UNIQUE,
    CONSTRAINT FK_FORNITORE   FOREIGN KEY (P_IVA_FORNITORE) REFERENCES FORNITORE (P_IVA_FORNITORE)  
);


--INVENTARIO
CREATE TABLE INVENTARIO ( 
    SKU             CHAR(13) PRIMARY KEY, 
    DESCRIZIONE_INV VARCHAR2(25) NOT NULL, 
    POSIZIONE       VARCHAR2(25) NOT NULL UNIQUE, 
    UNITA           VARCHAR2(25) NOT NULL, 
    QUANTITA_INV    NUMBER NOT NULL
);


--FORNITURA 
-- [SU FK2_FORNITORE NON HO AGGIUNTO NESSUNA POLITICA DI REAZIONE]
CREATE TABLE FORNITURA (  
    NUM_RICEVUTA_FORNITURA NUMBER PRIMARY KEY,
    P_IVA_FORNITORE        CHAR(11) NOT NULL,
    SKU                    CHAR(13), 
    DESCRIZIONE_FORNITURA  VARCHAR2(25) NOT NULL,
	QUANTITA_PALLET        NUMBER NOT NULL CHECK(QUANTITA_PALLET >0),
    CONSTRAINT FK2_FORNITORE FOREIGN KEY (P_IVA_FORNITORE) REFERENCES FORNITORE (P_IVA_FORNITORE),
    CONSTRAINT FK_INVENTARIO  FOREIGN KEY (SKU) REFERENCES INVENTARIO (SKU)  ON DELETE SET NULL
);



--CLIENTE (CON CHIAVE SURROGATA) UNION CON AZIENDA E PERSONA
-- [SU FK_CLIENTE E FK2_CLIENTE NON HO AGGIUNTO NESSUNA POLITICA DI REAZIONE]
CREATE TABLE CLIENTE ( 
    ID_CLIENTE       NUMBER PRIMARY KEY,
	TELEFONO_CLIENTE CHAR(17) NOT NULL UNIQUE,
	VIA_C            VARCHAR2(25) NOT NULL,
	CITTA_C          VARCHAR2(25) NOT NULL,
	CAP_C            CHAR(5) NOT NULL,
	NR_CIVICO_C      CHAR(3) NOT NULL
);


--SUPERCLASSE PERSONA CLIENTE
CREATE TABLE PERSONA ( 
    CF_PERSONA       CHAR(16), 
    ID_CLIENTE       NUMBER, 
    NOME_PERSONA     VARCHAR2(25), 
    COGNOME_PERSONA  VARCHAR2(25), 
	EMAIL_PERSONA    VARCHAR2(25) NOT NULL UNIQUE,
	CONSTRAINT PK_PERSONA PRIMARY KEY(CF_PERSONA, ID_CLIENTE), 
    CONSTRAINT FK_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE) 
);


--SUPERCLASSE AZIENDA CLIENTE
CREATE TABLE AZIENDA ( 
    P_IVA_CLIENTE    CHAR(11), 
    ID_CLIENTE       NUMBER, 
    NOME_AZIENDA     VARCHAR2(25), 
	DATA_FONDAZIONE  DATE,
	PEC              VARCHAR2(25) NOT NULL UNIQUE,
	CONSTRAINT PK_AZIENDA PRIMARY KEY(P_IVA_CLIENTE, ID_CLIENTE),
	CONSTRAINT FK2_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE) 
);


--CARTA
CREATE TABLE CARTA (
    NUM_CARTA           CHAR(19) PRIMARY KEY,
    ID_CLIENTE          NUMBER UNIQUE,
	DATA_SCADENZA_CARTA DATE NOT NULL,
	TIPO_CARTA          VARCHAR2(25),
    CONSTRAINT FK3_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE) ON DELETE SET NULL 
);


--PRODOTTO
-- [SU FK2_INVENTARIO NON HO AGGIUNTO NESSUNA POLITICA DI REAZIONE]
CREATE TABLE PRODOTTO ( 
    COD_A_BARRE CHAR(13) PRIMARY KEY, 
    SKU         CHAR(13) NOT NULL,
	ID_CLIENTE  NUMBER NOT NULL,
    MARCA       VARCHAR2 (25) NOT NULL,	
    TIPO        VARCHAR2 (25) NOT NULL, 
    MODELLO     VARCHAR2 (25) NOT NULL, 
	CONSTRAINT FK2_INVENTARIO FOREIGN KEY (SKU) REFERENCES INVENTARIO (SKU),
    CONSTRAINT FK4_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE) ON DELETE CASCADE 
);



--FATTURA
	--TIPO_CLIENTE 1: AZIENDA(QUINDI HA DIRITTO DI SCONTO)
	--TIPO_CLIENTE 2: PERSONA(ACQUISTI NORMALI)
CREATE TABLE FATTURA ( 
    NUM_FATTURA         NUMBER PRIMARY KEY, 
    DESCRIZIONE_FATTURA VARCHAR2(25) NOT NULL, 
    DESTINATARIO        VARCHAR2(25) NOT NULL, 
    QUANTITA_FATT       NUMBER NOT NULL,
    PREZZO_EURO         NUMBER NOT NULL,
	TIPO_CLIENTE        CHAR(1) NOT NULL, 
    PERCENTUALE_SCONTO  NUMBER, 
	CONSTRAINT CHECK_QUANTITA CHECK(QUANTITA_FATT>0),
	CONSTRAINT CHECK_TIPO_CLIENTE CHECK(TIPO_CLIENTE IN ('1','2')) 
);


--E'_IN (ASSOCIAZIONE: N PRODOTTO - M FATTURA)
CREATE TABLE E_IN ( 
   COD_A_BARRE CHAR(13), 
   NUM_FATTURA NUMBER,
   CONSTRAINT PK_E_IN PRIMARY KEY (COD_A_BARRE, NUM_FATTURA),
   CONSTRAINT FK_PRODOTTO FOREIGN KEY (COD_A_BARRE) REFERENCES PRODOTTO (COD_A_BARRE) ON DELETE CASCADE, 
   CONSTRAINT FK_FATTURA FOREIGN KEY (NUM_FATTURA) REFERENCES FATTURA (NUM_FATTURA) ON DELETE SET NULL

);


--REPARTO
CREATE TABLE REPARTO ( 
    NUM_REPARTO NUMBER PRIMARY KEY, 
    GENERE      VARCHAR2(25) NOT NULL UNIQUE,
	CONSTRAINT CHECK_GENERE CHECK(UPPER(GENERE) IN ('ABBIGLIAMENTO', 'CASALINGA', 'GIARDINAGGIO', 'EDILIZIA', 'BRICOLAGE', 'CARTOLERIA', 'BEVANDE', 'SPORT', 'AUTO', 'INFISSI', 'CAMPEGGIO', 'ELETTRONICA', 'ANIMALI', 'MUSICA', 'ILLUMINAZIONE'))
);


--ALLOCATO_IN (ASSOCIAZIONE: N PRODOTTO - M REPARTO)
-- [SU FK_REPARTO NON HO AGGIUNTO NESSUNA POLITICA DI REAZIONE]
CREATE TABLE ALLOCATO_IN ( 
    COD_A_BARRE CHAR(13), 
    NUM_REPARTO NUMBER,
    CONSTRAINT PK_ALLOCATO_IN PRIMARY KEY (COD_A_BARRE, NUM_REPARTO),	
    CONSTRAINT FK2_PRODOTTO FOREIGN KEY (COD_A_BARRE) REFERENCES PRODOTTO (COD_A_BARRE) ON DELETE CASCADE, 
    CONSTRAINT FK_REPARTO FOREIGN KEY (NUM_REPARTO) REFERENCES REPARTO (NUM_REPARTO) 
);


--MAGAZZINIERE
CREATE TABLE MAGAZZINIERE ( 
    CF_MAGAZZINIERE              CHAR(16) PRIMARY KEY, 
    NOME_MAGAZZINIERE            VARCHAR2(25), 
    COGNOME_MAGAZZINIERE         VARCHAR2(25), 
    TELEFONO_MAGAZZINIERE        CHAR(17) NOT NULL UNIQUE, 
    SESSO_MAGAZZINIERE           CHAR(1) NOT NULL, 
    DATA_ASSUNZIONE_MAGAZZINIERE DATE,
    TIPO_CONTRATTO_MAGAZZINIERE  VARCHAR(25) NOT NULL,
    CONSTRAINT CHECK_SESSO_MAGAZZINIERE CHECK(UPPER(SESSO_MAGAZZINIERE) IN ('M', 'F', 'N')),
    CONSTRAINT CHECK_TIPO_CONTRATTO_MAGAZZINIERE CHECK(UPPER(TIPO_CONTRATTO_MAGAZZINIERE) IN ('STAGE', 'APPRENDISTATO', 'INDETERMINATO')) 
);


--GESTISCE (ASSOCIAZIONE: N MAGAZZINIERE - M REPARTO)
-- [SU FK_MAGAZZINIERE E FK2_REPARTO NON HO AGGIUNTO NESSUNA POLITICA DI REAZIONE]
CREATE TABLE GESTISCE ( 
    CF_MAGAZZINIERE CHAR(16), 
    NUM_REPARTO     NUMBER, 
	CONSTRAINT PK_GESTISCE PRIMARY KEY (CF_MAGAZZINIERE, NUM_REPARTO), 
    CONSTRAINT FK_MAGAZZINIERE FOREIGN KEY (CF_MAGAZZINIERE) REFERENCES MAGAZZINIERE (CF_MAGAZZINIERE), 
    CONSTRAINT FK2_REPARTO FOREIGN KEY (NUM_REPARTO) REFERENCES REPARTO (NUM_REPARTO) 
);


--AUTISTA
CREATE TABLE AUTISTA ( 
    CF_AUTISTA              CHAR(16) PRIMARY KEY, 
    NOME_AUTISTA            VARCHAR2(25), 
    COGNOME_AUTISTA         VARCHAR2(25), 
    TELEFONO_AUTISTA        CHAR(17) NOT NULL UNIQUE, 
    SESSO_AUTISTA           CHAR(1) NOT NULL, 
    DATA_ASSUNZIONE_AUTISTA DATE NOT NULL,
	DATA_NASCITA_AUTISTA    DATE NOT NULL,
	TIPO_CONTRATTO_AUTISTA  VARCHAR(25) NOT NULL,
	CONSTRAINT CHECK_SESSO  CHECK(UPPER(SESSO_AUTISTA) IN ('M','F', 'N')),
	CONSTRAINT CHECK_TIPO_CONTRATTO_AUTISTA CHECK(UPPER(TIPO_CONTRATTO_AUTISTA) IN ('STAGE', 'APPRENDISTATO', 'INDETERMINATO')) 
);


--CAMION
-- [SU FK_AUTISTA NON HO AGGIUNTO NESSUNA POLITICA DI REAZIONE]
CREATE TABLE CAMION (
    TARGA          CHAR(7) PRIMARY KEY,
    CF_AUTISTA     CHAR (16) NOT NULL,
	MARCA_CAMION   VARCHAR2(25),
    MODELLO_CAMION VARCHAR2(25),
    CILINDRATA     VARCHAR2(25),
    POTENZA        VARCHAR2(25),
    CONSTRAINT FK_AUTISTA FOREIGN KEY (CF_AUTISTA) REFERENCES AUTISTA(CF_AUTISTA)
);


--ORDINE
-- [SU FK2_AUTISTA NON HO AGGIUNTO NESSUNA POLITICA DI REAZIONE]
CREATE TABLE ORDINE ( 
    NUM_ORDINE  CHAR(9) PRIMARY KEY, 
    ID_CLIENTE  NUMBER UNIQUE, 
    CF_AUTISTA  CHAR(16), 
    DATA_ORDINE DATE NOT NULL, 
    CONSTRAINT FK5_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE) ON DELETE CASCADE, 
    CONSTRAINT FK2_AUTISTA FOREIGN KEY (CF_AUTISTA) REFERENCES AUTISTA (CF_AUTISTA)
);


--SPEDIZIONE 
CREATE TABLE SPEDIZIONE ( 
    TRACKING_           CHAR(19), 
    NUM_ORDINE          CHAR(9),
    DATA_CONSEGNA       DATE NOT NULL,
	STATO_SPEDIZIONE    VARCHAR2(25) DEFAULT 'IN PARTENZA',
	PRIORITA_SPEDIZIONE VARCHAR2(25) DEFAULT 'BASSA',
	CONSTRAINT CHECK_STATO_SPEDIZIONE CHECK(UPPER(STATO_SPEDIZIONE) IN ('IN PARTENZA', 'IN CONSEGNA', 'IN RITARDO', 'TERMINATO')),
	CONSTRAINT CHECK_PRIORITA_SPEDIZIONE CHECK(UPPER(PRIORITA_SPEDIZIONE) IN ('BASSA', 'NORMALE', 'URGENTE')),
    CONSTRAINT PK_SPEDIZIONE PRIMARY KEY (TRACKING_, NUM_ORDINE), 	
    CONSTRAINT FK_ORDINE FOREIGN KEY (NUM_ORDINE) REFERENCES ORDINE (NUM_ORDINE) ON DELETE SET NULL
);
