
--Gli autisti devono essere maggiorenni per poter guidare i camion ed effettuare consegne.

-- Evento DML: INSERT INTO
-- Tabella di appoggio: AUTISTA
-- Temporizzazione: BEFORE INSERT


--Intestazione
CREATE OR REPLACE TRIGGER Autisti_Minorenni
BEFORE INSERT ON AUTISTA
FOR EACH ROW

DECLARE
    MINORENNE EXCEPTION;

BEGIN
    --CODICE CHE GESTISCE L'INSERIMENTO
    IF INSERTING THEN
        IF FLOOR((SYSDATE - :NEW.DATA_NASCITA_AUTISTA)/365)<18 THEN
            RAISE MINORENNE;
        END IF;
    END IF;

EXCEPTION
    WHEN MINORENNE THEN
         RAISE_APPLICATION_ERROR(-20000, 'Attenzione, l autista è minorenne!');
		 
END;

--TEST:

--INSERT INTO AUTISTA (CF_AUTISTA, NOME_AUTISTA, COGNOME_AUTISTA, TELEFONO_AUTISTA, SESSO_AUTISTA, DATA_ASSUNZIONE_AUTISTA, DATA_NASCITA_AUTISTA, TIPO_CONTRATTO_AUTISTA) VALUES ('22RGFDGD366462', 'PIPPO', 'TOPOLINO', '+212 737 519 3266', 'M', TO_DATE('17/08/2022', 'DD/MM/YYYY'), TO_DATE('09/12/2022', 'DD/MM/YYYY'), 'APPRENDISTATO');
