--all'inserimento di clienti con Partita Iva gli attributi devono essere unici tra loro


-- Evento DML: INSERT INTO
-- Tabella di appoggio: AZIENDA
-- Temporizzazione: BEFORE INSERT OR UPDATE


--Intestazione
CREATE OR REPLACE TRIGGER Check_Azienda
BEFORE INSERT OR UPDATE ON AZIENDA
FOR EACH ROW

DECLARE
	CONT NUMBER;
	ERROR_OVERLAP EXCEPTION;
	
BEGIN
	--Codice che gestisce l'inserimento
	IF INSERTING THEN
		SELECT COUNT(*) INTO CONT 
		FROM AZIENDA
		WHERE AZIENDA.ID_CLIENTE = :NEW.ID_CLIENTE
			OR AZIENDA.P_IVA_CLIENTE = :NEW.P_IVA_CLIENTE
			OR AZIENDA.NOME_AZIENDA = :NEW.NOME_AZIENDA
			OR AZIENDA.PEC=:NEW.PEC;

		IF CONT <> 0 THEN
			RAISE ERROR_OVERLAP;
		END IF;
END IF;
    
EXCEPTION
	WHEN ERROR_OVERLAP THEN
		RAISE_APPLICATION_ERROR(-20003, 'Attenzione, i dati delle Partite Iva devono essere unici tra loro!');
END;

--TEST:

--LANCIARE PRIMA LO SCRIPT DML

--INSERT INTO AZIENDA (P_IVA_CLIENTE, ID_CLIENTE, NOME_AZIENDA, DATA_FONDAZIONE, PEC)  VALUES ('44936197739', 40, 'WILDERMAN AND SONS', TO_DATE('01/1960', 'MM/YYYY'), 'GCRISTOFOLOJ@GODADDY.COM');
