-- Avvia_Fornitura

CREATE OR REPLACE PROCEDURE Avvia_Fornitura (NUM_RICEVUTA_FORNITURA1 NUMBER, P_IVA_FORNITORE CHAR, SKU CHAR, DESCRIZIONE_FORNITURA VARCHAR, QUANTITA_PALLET NUMBER)
IS
	verifica_fornitura NUMBER;
	errore1 EXCEPTION;

BEGIN
	INSERT INTO FORNITURA VALUES (NUM_RICEVUTA_FORNITURA1, P_IVA_FORNITORE, SKU, DESCRIZIONE_FORNITURA, QUANTITA_PALLET);

	SELECT COUNT(NUM_RICEVUTA_FORNITURA) INTO verifica_fornitura
	FROM FORNITURA
	WHERE NUM_RICEVUTA_FORNITURA = NUM_RICEVUTA_FORNITURA1;
	
	IF verifica_fornitura = 1 THEN
		DBMS_OUTPUT.PUT_LINE('Fornitura avviata con successo!');
	ELSE
		RAISE errore1;
	END IF;

EXCEPTION
	WHEN errore1 THEN
		RAISE_APPLICATION_ERROR(-20010,'Errore durante l'' inserimento!');

END;



--EXECUTE Avvia_Fornitura (777, '14585146513','SP7875', 'ARTICOLI TEST' , 6);