
-- Calcola il costo e sconto totale nella fattura

CREATE OR REPLACE PROCEDURE Calcola_Totale (NUM_FATTURA1 NUMBER)
IS

    TOT_COSTO   NUMBER;
    PERCENTUALE NUMBER;
	SOTT        NUMBER;

BEGIN

    SELECT SUM(PREZZO_EURO*QUANTITA_FATT) INTO TOT_COSTO
    FROM FATTURA
    WHERE NUM_FATTURA = NUM_FATTURA1;
    
    SELECT SUM(PERCENTUALE_SCONTO) INTO PERCENTUALE
    FROM FATTURA
    WHERE NUM_FATTURA = NUM_FATTURA1;
	
	SOTT := (TOT_COSTO*PERCENTUALE)/100;
	TOT_COSTO := TOT_COSTO - SOTT;

    DBMS_OUTPUT.PUT_LINE('Il totale della spesa e: ' || TOT_COSTO);
    DBMS_OUTPUT.PUT_LINE('Sconto totale della spesa e: ' || SOTT);

END;
	
-- EXECUTE Calcola_Totale (962);