
-- Eliminare dal DB tutte le carte scadute

CREATE OR REPLACE PROCEDURE Cancella_Carte_Scadute 
IS 
	CARTE_SCADUTE NUMBER; 
	
BEGIN 
	FOR R IN 
	( 
		SELECT NUM_CARTA 
		FROM CARTA 
		WHERE CARTA.DATA_SCADENZA_CARTA < SYSDATE  
	)
	
		LOOP 
			DELETE FROM CARTA 
			WHERE CARTA.DATA_SCADENZA_CARTA = R.NUM_CARTA; 
		END LOOP; 
		
END;

--INSERT INTO CARTA (NUM_CARTA, ID_CLIENTE, DATA_SCADENZA_CARTA, TIPO_CARTA) VALUES ('201937308582337', 40, TO_DATE('10/2022', 'MM/YYYY'), 'DINERS-CLUB-ENROUTE');

-- EXECUTE Cancella_Carte_Scadute;