--Visualizza spedizioni a carico degli autisti, 

CREATE VIEW Autisti_Spedizioni AS
(
SELECT AUT.NOME_AUTISTA, AUT.COGNOME_AUTISTA, ORD.NUM_ORDINE, SP.DATA_CONSEGNA, SP.TRACKING_ AS COD_TRACCIAMENTO 
FROM ((AUTISTA AUT JOIN ORDINE ORD ON AUT.CF_AUTISTA = ORD.CF_AUTISTA)
                   JOIN SPEDIZIONE SP ON ORD.NUM_ORDINE = SP.NUM_ORDINE)

);

--SELECT * FROM AUTISTI_SPEDIZIONI;
