--Clienti Con Partita Iva visualizzano i prodotti

CREATE VIEW Clienti_con_Iva_Prodotti AS
(
SELECT CL.ID_CLIENTE, AZ.NOME_AZIENDA, PROD.MARCA, PROD.TIPO, PROD.MODELLO
FROM ((CLIENTE CL JOIN PRODOTTO PROD ON CL.ID_CLIENTE = PROD.ID_CLIENTE)
                  JOIN AZIENDA AZ ON CL.ID_CLIENTE = AZ.ID_CLIENTE)
);

--SELECT * FROM CLIENTI_CON_IVA_PRODOTTI