
--Lista di Magazzinieri che gestiscono opportuni reparti

CREATE VIEW Lista_Magazzinieri_Reparti AS
(
SELECT MAG.NOME_MAGAZZINIERE, GEST.NUM_REPARTO, REP.GENERE
FROM (MAGAZZINIERE MAG JOIN GESTISCE GEST ON MAG.CF_MAGAZZINIERE = GEST.CF_MAGAZZINIERE
                       JOIN REPARTO REP ON GEST.NUM_REPARTO = REP.NUM_REPARTO)
);

--SELECT * FROM LISTA_MAGAZZINIERI_REPARTI



