--CREAZIONE UTENTI

CREATE USER DB_AMM       IDENTIFIED BY vOmDZHR2wF1dJy2a;
CREATE USER MAGAZZINIERE IDENTIFIED BY W4upChd8KKdaWlj9;
CREATE USER AUTISTA      IDENTIFIED BY CmY8YUYFxKPK4TOa;
CREATE USER FORNITORE    IDENTIFIED BY eXFZ1pgwN3I1SBFN;
CREATE USER CLIENTE      IDENTIFIED BY DEIvDd7c3Ry1nrZ1;

GRANT ALL PRIVILEGES TO DB_AMM;
